# Hello Python

Variables merupakan suatu nama yang merujuk pada suatu data atau kumpulan data. 
Variabel dapat mewakili beragai type data.
Variabel bisa berubah secara dinamis

# Data Structures

## List

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

List hanya bisa ditambahkan dengan list tidak bisa dengan angka saja atau integer saja

In [2]:
my_list + 4

TypeError: can only concatenate list (not "int") to list

In [4]:
my_list + [4.5]

[1, 2, 3, 4.5]

In [5]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [6]:
my_list.append(4)
my_list

[1, 2, 3, 4]

In [7]:
my_list.append(4,5)

TypeError: list.append() takes exactly one argument (2 given)

In [17]:
my_list.append([4,5])
my_list

[1, 2, 3, 4, [4, 5]]

In [12]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [13]:
mylist.extend([4,5,6])
mylist

[1, 2, 3, 4, 5, 6]

In [18]:
my_list.remove([4,5])
my_list

[1, 2, 3, 4]

In [19]:
mylist.remove(4)
mylist

[1, 2, 3, 5, 6]

## Dictionaries

Lebih fleksibel karena menggunakan key dan value

In [25]:
student = {'name': 'Raka', 'age' : 18}
employee = {'cto': {'name':'raka','age':'18'}}
print(student , employee)

{'name': 'Raka', 'age': 18} {'cto': {'name': 'raka', 'age': '18'}}


In [26]:
student=dict(name='Billy',age=38)
student

{'name': 'Billy', 'age': 38}

In [27]:
print(student['name'])

Billy


In [28]:
print(student['age'])

38


In [30]:
print(student)

{'name': 'Billy', 'age': 38}


In [31]:
del student['age']
student

{'name': 'Billy'}

In [32]:
student = {'name':'Raka','age':17}
student.keys()

dict_keys(['name', 'age'])

In [33]:
student.values()

dict_values(['Raka', 17])

Dictionary tidak bersifat berurutan, tipe data bisa menggunakan type data lain

## Tuples

tuples menggunakan tanda kurung () diawal dan diakhir, mengaksesnya menggunakan index, dan datanya tidak bisa diubah-ubah (imuteable)

In [35]:
people = ('Raka',('kode','random'))
people

('Raka', ('kode', 'random'))

In [39]:
print(people[1])
print(people[0])
print(people[1][0])
print(people[1][1])

('kode', 'random')
Raka
kode
random


In [41]:
numbers = (1,2,3,4)
new_numbers = numbers[0],numbers[1:3]
print(numbers, new_numbers)

(1, 2, 3, 4) (1, (2, 3))


jika melakukan operasi pada tuples maka akan membuat tuples baru tidak mempengaruhi tuples sebelumnya

In [42]:
email_attr = ('to','from','cc','bcc','subject','body')
email_attr_list = list(email_attr)
email_attr_list.sort()
email_attr_list

['bcc', 'body', 'cc', 'from', 'subject', 'to']

## Files

Python bisa membuka file dengan beberapa mode read, write, append, binary, dan +.

In [43]:
myfile = open('text.txt','w')

In [44]:
myfile.write('Hello World !\n')

14

In [45]:
myfile.write('Selamat Tinggal text file!\n')

27

baru dibuffer dimemori dan belum disimpan dalam file sehingga harus diclose

In [46]:
myfile.close()

In [48]:
myfile = open('text.txt')

In [49]:
myfile.readline()

'Hello World !\n'

In [50]:
myfile.readline()

'Selamat Tinggal text file!\n'

In [52]:
open('text.txt').read()

'Hello World !\nSelamat Tinggal text file!\n'

In [53]:
print(open('text.txt').read())

Hello World !
Selamat Tinggal text file!



Files hanya bisa menerima type data dalam string, sehingga seluruh data harus diubah menjadi string

In [55]:
x,y,z = 43,44,45
massage = 'Spam'
data = {'a':1,'b':2}
list = [1,2,3]

In [56]:
file = open('text.txt', 'w')

In [57]:
file.write(massage + '\n')

5

In [58]:
file.write('%s, %s, %s\n' %(x,y,z))

11

In [59]:
file.write(str(list)+ '$' + str(data) + '\n')

27

In [60]:
file.close()

In [61]:
print(open('text.txt').read())

Spam
43, 44, 45
[1, 2, 3]${'a': 1, 'b': 2}



# Loop & Iterators

## While Loops

iterasi yang paling umum, terus melakukan pengulangan selama kondisi pertama terpenuhi

In [63]:
message = "spam"
while message != '':
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [64]:
message = "spam"
while message:
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [65]:
a = 0
b = 13
while a<b:
    print(a, end=' ')
    a=a+1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [67]:
while True: 
    name = input('Enter name: ')
    if name == 'stop':break
    age = input('Enter age: ')
    print('Hello', name, '=>',int(age)**2)

Enter name:  ha
Enter age:  2


Hello ha => 4


Enter name:  hi
Enter age:  3


Hello hi => 9


Enter name:  hu
Enter age:  4


Hello hu => 16


Enter name:  stop


## For Loops

For diawali dengan target dari suatu objek atau variabel 

In [68]:
for word in ['raka','billy','kode']:
    print(word, end='\n')

raka
billy
kode


In [69]:
sum = 0
for i in [1,2,3,4]:
    sum=sum+i
sum

10

In [71]:
prod = 1
for item in [1,2,3,4]: prod *= item
prod

24

In [72]:
text = 'foxy fox'
words = ('is','great','animal')
for chara in text: print(chara, end=' ')

f o x y   f o x 

In [73]:
for word in words: print(word, end='...')

is...great...animal...

For looping bisa digunakan untuk berbagai type data

In [74]:
accor = [(1,2),(3,4),(5,6)]
for(x,y)in accor: print(x,y)

1 2
3 4
5 6


# Branching in Python

# If Statement

if erat dengan type data bolean yaitu true dan false`r 

In [77]:
if 1: #(angka 1 artinya bolean = true)
    print('true')

true


In [78]:
if not 1:
    print('true')
else: 
    print('false')

false


In [92]:
age = input('Enter age: ')
if int(age)*300>20000:
    print('Time to retire!')
elif int(age)*365>10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter age:  5


Time to get started!


In [95]:
user_age = input('Enter your age: ')
age=int(user_age)*365

if age>= 9490:
    print('You are a Jedi Master now. Go learn from master yoda!!!')
elif age>= 8395 and age<9490:
    print('Become Jedi Knight')
else:
    print('You are a young Pandawas')

Enter your age:  50


You are a Jedi Master now. Go learn from master yoda!!!


# Functions & Packages

## Functions

sekumpuluan perintah yang bisa digunakan berulang-ulang

runtutan perintah yang bisa digunakan untuk mengerjakan suatu kode pemrograman dengan hanya memanggil function tersebut

In [96]:
def add(a,b):
    return a+b

In [97]:
add(5,4)

9

In [98]:
add_things = add(10,4)

In [100]:
add_things

14

In [101]:
def add_and_print(a,b):
    print(a+b)

In [102]:
add_and_print(1,3)

4


In [103]:
x = add_and_print(5,3)

8


In [104]:
print(x)

None


In [105]:
def intersection(first_word, second_word):
    result = []
    for x in first_word:
        if x in second_word:
            result.append(x)
    return result

In [106]:
word1 = 'spam'
word2 = 'scam'
char_of_intersect = intersection(word1 ,word2)
print(char_of_intersect)

['s', 'a', 'm']


jika ada return maka function akan mengembalikan nilai tersebut

## Modules & Built-in Function

built in Function adalah function yang dibuat oleh para kontributor python yang bisa kita gunakan

In [107]:
print(abs(-123))

123


In [121]:
numbers = [1,2,3]
print(isinstance(numbers, tuple))

False


In [123]:
print(isinstance(numbers, dict))

False


In [125]:
numbers = [1,2,3,4,5,6,7]
print(max(numbers))
print(min(numbers))

7
1


In [127]:
alphas=['a','b','z']
print(max(alphas))
print(min(alphas))

z
a


In [129]:
languages = ['py','js','go','c']
print(languages.index('go'))

2


In [130]:
languages.sort()
languages

['c', 'go', 'js', 'py']

In [131]:
name = 'raka'
name.replace('a','i')

'riki'

In [132]:
name.capitalize()

'Raka'

In [133]:
name.upper()

'RAKA'

In [136]:
name.lower()

'raka'

## Packages

Thirth party library atau contributor eksternal yang membuat packages

In [138]:
!pip3 -V

pip 22.3.1 from E:\Anaconda3\lib\site-packages\pip (python 3.10)



In [148]:
!pip3 install requests

In [140]:
import requests 

In [142]:
r = requests.get('https://api.github.com/events')
print(r.status_code)

200


In [149]:
print(r.json())

[{'id': '28363321815', 'type': 'CreateEvent', 'actor': {'id': 89629698, 'login': 'mikaelgus', 'display_login': 'mikaelgus', 'gravatar_id': '', 'url': 'https://api.github.com/users/mikaelgus', 'avatar_url': 'https://avatars.githubusercontent.com/u/89629698?'}, 'repo': {'id': 626916622, 'name': 'mikaelgus/mahdmaisbck', 'url': 'https://api.github.com/repos/mikaelgus/mahdmaisbck'}, 'payload': {'ref': 'main', 'ref_type': 'branch', 'master_branch': 'main', 'description': None, 'pusher_type': 'user'}, 'public': True, 'created_at': '2023-04-12T12:21:52Z'}, {'id': '28363321806', 'type': 'PullRequestEvent', 'actor': {'id': 84877045, 'login': 'DanilLevkov', 'display_login': 'DanilLevkov', 'gravatar_id': '', 'url': 'https://api.github.com/users/DanilLevkov', 'avatar_url': 'https://avatars.githubusercontent.com/u/84877045?'}, 'repo': {'id': 581105321, 'name': 'spbu-se/mag_practices_2022-2024', 'url': 'https://api.github.com/repos/spbu-se/mag_practices_2022-2024'}, 'payload': {'action': 'opened', 'n

!pip3 install -r requirements.txt (untuk menginstall packages keseluruhan)

# Bonus Chapter

## Pengenalan NumPy

In [154]:
height = [1.75,1.68,1.8,1.81,1.60]
weight = [66.4,49.22,66.3,88.56,65.4]
weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [151]:
import numpy as np

In [156]:
np_height=np.array(height)
np_weight=np.array(weight)
bmi = np_weight/np_height **2
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 25.546875  ])

hanya boleh mengandung satu type data

In [157]:
mixed_array =np.array([1.0, 'is', True])
mixed_array

array(['1.0', 'is', 'True'], dtype='<U32')

In [158]:
numlist = [1,2,3]
nparray = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [159]:
bmi > 24

array([False, False, False,  True,  True])

In [160]:
bmi[bmi>24]

array([27.03214188, 25.546875  ])

## Statistik Dasar dengan NumPy

In [165]:
height = np.round(np.random.normal(1.755,0.2,5000),2)
height

array([1.83, 1.65, 1.91, ..., 1.77, 1.86, 1.55])

In [166]:
len(height)

5000

In [167]:
weight = np.round(np.random.normal(60.32,15,5000),2)

In [169]:
len(weight)

5000

In [170]:
np_city = np.column_stack((height, weight))
np.mean(np_city[:,0])

1.752752

In [171]:
np.median(np_city[:,0])

1.75

In [172]:
np.std(np_city[:,0])

0.20313371580316253

## NumPy Array 2D

In [173]:
height = np.array([1.75,1.68,1.8])
weight = np.array([66.4, 49.22, 66.3])
type(height)

numpy.ndarray

In [174]:
np_2d = np.array([[1.75,1.68,1.8],[66.4, 49.22, 66.3]])
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [175]:
np_2d.shape

(2, 3)

In [176]:
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [177]:
np_2d[0][2]

1.8

In [178]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [179]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 ])